services:
  web_app:
    build: ./Web_App
    ports:
      - "5054:80"
    volumes:
      - ./Web_App:/usr/local/apache2/htdocs/

  fc_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: dpp_fc_db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./FC_DB_data:/data/db
    ports:
      - "5053:27017"

  fc_service:
    build: ./FC_Service
    ports:
      - "5052:5052"
    volumes:
      - ./FC_Service:/usr/src/app
      - /usr/src/app/node_modules

  #lta_service:
  #  build: ./LTA_service
  #  ports:
  #    - "5050:5050"
  #  volumes:
  #    - ./LTA_service:/usr/src/app
    
  dpp_service:
    build: ./DPP_service
    volumes:
      - ./DPP_service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5051:5051"

