services:
  lta_service:
    build: ./LTA_service
    ports:
      - "5050:5050"
    volumes:
      - ./LTA_service:/usr/src/app
    
  dpp_service:
    build: ./DPP_service
    volumes:
      - ./DPP_service:/usr/src/app
    ports:
      - "5051:5051"